version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=users
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: